services:
  postgres:
    image: postgres:15
    container_name: jobtracker-postgres
    environment:
      POSTGRES_DB: jobtracker_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: jobtracker-app
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/jobtracker_pro
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-secret-key-here
      - NODE_ENV=production
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 